[package]
name = "async_limiter"
description = "Simple ratelimiter for async tasks."
version = "0.1.1"
edition = "2024"
license = "MIT"

[dev-dependencies]
tokio = { version = "1.44.1", features = ["full"] }
